[package]
name = "cookie-auth"
version = "3.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.5", features = ["tokio"] }
ntex-identity = "0.2"
env_logger = "0.10"
