[package]
name = "json_error"
version = "2.0.0"
authors = ["Kai Yao <kai.b.yao@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.5", features = ["tokio"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
