[package]
name = "basics"
version = "3.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.5", features = ["tokio"] }
ntex-files = "0.2"
ntex-session = "0.2"
futures = "0.3"
env_logger = "0.10"
