[package]
name = "static_index"
version = "3.0.0"
authors = ["Jose Marinez <digeratus@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
env_logger = "0.10"

ntex = { version = "0.6.5", features = ["tokio"] }
ntex-files = "0.2"
