[package]
name = "hello-world"
version = "3.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.5", features = ["tokio"] }
env_logger = "0.10"
