[package]
name = "shutdown-server"
version = "3.0.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2018"
description = "Send a request to the server to shut it down"

[dependencies]
ntex = { version = "0.6.5", features = ["tokio"] }
env_logger = "0.10"
futures = "0.3"
