[package]
name = "docker_sample"
version = "0.2.0"
authors = ["docker_sample <docker_sample@sample.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntex = { version = "0.6.5", features = ["tokio"] }
